# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: matheus-pxt@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
